cmake_minimum_required(VERSION 3.24)
project(atomic_time LANGUAGES CXX CUDA)
set(CMAKE_CUDA_ARCHITECTURES native)
add_executable(atomic_time atomic_time.cu)
target_compile_features(atomic_time PRIVATE cxx_std_17 cuda_std_17)
enable_testing()
add_test(NAME atomic_time_validation COMMAND atomic_time)
add_executable(region_cache region_cache.cu)
target_compile_features(region_cache PRIVATE cxx_std_17 cuda_std_17)
add_test(NAME region_cache_validation COMMAND region_cache)
